/**
 * Planning Poker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const CardValue = {
    ZERO: 'ZERO',
    ONE: 'ONE',
    TWO: 'TWO',
    THREE: 'THREE',
    FIVE: 'FIVE',
    EIGHT: 'EIGHT',
    THIRTEEN: 'THIRTEEN',
    TWENTY_ONE: 'TWENTY_ONE',
    THIRTY_FOUR: 'THIRTY_FOUR',
    QUESTION: 'QUESTION',
    COFFEE: 'COFFEE'
} as const;
export type CardValue = typeof CardValue[keyof typeof CardValue];

