/**
 * Planning Poker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Vote } from './vote';
import { CardValue } from './cardValue';


export interface Round { 
    issueIid?: number;
    votes?: Array<Vote>;
    finalValue?: CardValue;
}
export namespace Round {
}


