/**
 * Planning Poker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const SessionStatus = {
    WAITING: 'WAITING',
    VOTING: 'VOTING',
    REVEALED: 'REVEALED'
} as const;
export type SessionStatus = typeof SessionStatus[keyof typeof SessionStatus];

