/**
 * Planning Poker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CardValue } from './cardValue';


export interface VoteRequest { 
    value: CardValue;
}
export namespace VoteRequest {
}


