quarkus.http.non-application-root-path=/q
quarkus.http.enable-compression=true

# OpenAPI + Swagger UI
quarkus.smallrye-openapi.info-title=Planning Poker API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Backend API for the Planning Poker application
quarkus.swagger-ui.always-include=true

# GitLab REST client base URL
quarkus.rest-client.gitlab-api.url=https://gitlab.com/api/v4
